- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Creates /etc/hosts file
  template: 
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root

- name: Sets hostname in /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    mode: 0644
    owner: root
    group: root

- name: Check if cloud config is present
  stat:
    path: /etc/cloud/cloud.cfg
  register: __cloud_config
  when: hosts_fix_cloud_config

- name: Ensure manage_etc_hosts is false if cloud config exists
  lineinfile:
    regexp: '^manage_etc_hosts:'
    line: "manage_etc_hosts: true"
  when: hosts_fix_cloud_config and __cloud_config.stat.exists